### ISSUE TITLE
Config YAMLs not included in built package

### ISSUE THREAD

**Issue by sellth** [ghga-de/ghga-transpiler#36]
Package bundles published on PyPI do not include the `*.yaml` files of `src/ghga_transpiler/configs/`. As these files are required for ghga-transpiler to function, a somewhat non-descriptive error is thrown:

```
$ ghga-transpiler ~/ghga_submission_test.xlsx
Unable to parse input file 'ghga_submission_minimal.xlsx': Unknown metadata version: 1.1
```

## Solution
As per [setuptools documentation](https://setuptools.pypa.io/en/latest/userguide/miscellaneous.html), non-python files have to be specifically included in the build, for example via `MANIFEST.in`.

**Comment by sbilge** [comment]
Thank you @sellth. #46 fixed the issue.
